const sampleData  = [
    
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Ayesha Rahman", "description": "MBBS, MD (Gynecology)", "specialist": "Gynecologist", "division": "Dhaka", "location": "Dhaka, City Hospital", "booking_amount": { "new": 1000, "old": 500 }, "booking": 1961829701, "email": "ayesha.rahman@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Mohammad Hasan", "description": "MBBS, MD (Pediatrics)", "specialist": "Pediatrician", "division": "Chittagong", "location": "Chittagong, Children's Hospital", "booking_amount": { "new": 1200, "old": 600 }, "booking": 1961829702, "email": "mohammad.hasan@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Fatima Ahmed", "description": "MBBS, MD (Cardiology)", "specialist": "Cardiologist", "division": "Khulna", "location": "Khulna, Heart Care Center", "booking_amount": { "new": 1100, "old": 550 }, "booking": 1961829703, "email": "fatima.ahmed@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Arif Hossain", "description": "MBBS, MD (Dermatology)", "specialist": "Dermatologist", "division": "Rajshahi", "location": "Rajshahi, Skin Clinic", "booking_amount": { "new": 1300, "old": 650 }, "booking": 1961829704, "email": "arif.hossain@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Shabnam Sultana", "description": "MBBS, MD (Orthopedics)", "specialist": "Orthopedic Surgeon", "division": "Sylhet", "location": "Sylhet, Bone and Joint Hospital", "booking_amount": { "new": 1400, "old": 700 }, "booking": 1961829705, "email": "shabnam.sultana@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Rafiqur Rahman", "description": "MBBS, MD (Neurology)", "specialist": "Neurologist", "division": "Barisal", "location": "Barisal, Brain Health Center", "booking_amount": { "new": 1500, "old": 750 }, "booking": 1961829706, "email": "rafiqur.rahman@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Nabila Khan", "description": "MBBS, MD (Endocrinology)", "specialist": "Endocrinologist", "division": "Narayanganj", "location": "Narayanganj, Diabetes Care Clinic", "booking_amount": { "new": 1600, "old": 800 }, "booking": 1961829707, "email": "nabila.khan@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Tanvir Ahmed", "description": "MBBS, MD (Gastroenterology)", "specialist": "Gastroenterologist", "division": "Comilla", "location": "Comilla, Digestive Health Center", "booking_amount": { "new": 1700, "old": 850 }, "booking": 1961829708, "email": "tanvir.ahmed@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Sultana Begum", "description": "MBBS, MD (Ophthalmology)", "specialist": "Ophthalmologist", "division": "Mymensingh", "location": "Mymensingh, Eye Hospital", "booking_amount": { "new": 1800, "old": 900 }, "booking": 1961829709, "email": "sultana.begum@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Kamal Hossain", "description": "MBBS, MD (Urology)", "specialist": "Urologist", "division": "Pabna", "location": "Pabna, Urology Clinic", "booking_amount": { "new": 1900, "old": 950 }, "booking": 1961829710, "email": "kamal.hossain@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Jahanara Begum", "description": "MBBS, MD (Psychiatry)", "specialist": "Psychiatrist", "division": "Brahmanbaria", "location": "Brahmanbaria, Mental Health Center", "booking_amount": { "new": 2000, "old": 1000 }, "booking": 1961829711, "email": "jahanara.begum@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Imran Chowdhury", "description": "MBBS, MD in Oncology", "specialist": "Oncologist", "division": "Narsingdi", "location": "Narsingdi Cancer Care Center", "booking_amount": { "new": 2100, "old": 1050 }, "booking": 112324342, "email": "imran.chowdhury@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Nusrat Jahan", "description": "MBBS, MD in Rheumatology", "specialist": "Rheumatologist", "division": "Cox's Bazar", "location": "Cox's Bazar Joint Health Clinic", "booking_amount": { "new": 2200, "old": 1100 }, "booking": 11332434223, "email": "nusrat.jahan@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Saifur Rahman", "description": "MBBS, MD in Pulmonology", "specialist": "Pulmonologist", "division": "Tangail", "location": "Tangail Lung Health Center", "booking_amount": { "new": 2300, "old": 1150 }, "booking": 114324324, "email": "saifur.rahman@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Rina Akter", "description": "MBBS, MD in Hematology", "specialist": "Hematologist", "division": "Jashore", "location": "Jashore Blood Health Clinic", "booking_amount": { "new": 2400, "old": 1200 }, "booking": 1155214553, "email": "rina.akter@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Shakib Al Hasan", "description": "MBBS, MD in Nephrology", "specialist": "Nephrologist", "division": "Netrakona", "location": "Netrakona Kidney Care Center", "booking_amount": { "new": 2500, "old": 1250 }, "booking": 116232352, "email": "shakib.al.hasan@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Sumaiya Rahman", "description": "MBBS, MD in Allergy and Immunology", "specialist": "Allergist", "division": "Panchagarh", "location": "Panchagarh Allergy Clinic", "booking_amount": { "new": 2600, "old": 1300 }, "booking": 1172323523, "email": "sumaiya.rahman@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Rifat Hossain", "description": "MBBS, MD in Family Medicine", "specialist": "Family Physician", "division": "Bogra", "location": "Bogra Family Health Center", "booking_amount": { "new": 2700, "old": 1350 }, "booking": 118, "email": "rifat.hossain@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Shirin Akhter", "description": "MBBS, MD in Infectious Diseases", "specialist": "Infectious Disease specialist", "division": "Khulna", "location": "Khulna Infectious Disease Hospital", "booking_amount": { "new": 2800, "old": 1400 }, "booking": 119322352, "email": "shirin.akhter@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Ahsan Habib", "description": "MBBS, MD in Sports Medicine", "specialist": "Sports Medicine specialist", "division": "Dhaka", "location": "Dhaka Sports Medicine Center", "booking_amount": { "new": 2900, "old": 1450 }, "booking": 1203223432, "email": "ahsan.habib@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Shabir Ahmed", "description": "MBBS, MD in Geriatrics", "specialist": "Geriatrician", "division": "Mymensingh", "location": "Mymensingh Geriatric Care Center", "booking_amount": { "new": 3000, "old": 1500 }, "booking": 121324324, "email": "shabir.ahmed@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Farzana Akter", "description": "MBBS, MD in Nutrition", "specialist": "Nutritionist", "division": "Rajshahi", "location": "Rajshahi Nutrition Clinic", "booking_amount": { "new": 3100, "old": 1550 }, "booking": 122522521, "email": "farzana.akter@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Ruma Sultana", "description": "MBBS, MD in Pain Management", "specialist": "Pain Management specialist", "division": "Barisal", "location": "Barisal Pain Management Center", "booking_amount": { "new": 3200, "old": 1600 }, "booking": 1234565767, "email": "ruma.sultana@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Kamal Uddin", "description": "MBBS, MD in Palliative Care", "specialist": "Palliative Care specialist", "division": "Sylhet", "location": "Sylhet Palliative Care Center", "booking_amount": { "new": 3300, "old": 1650 }, "booking": 124685756, "email": "kamal.uddin@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Ameer Hossain", "description": "MBBS, MD in Medical Genetics", "specialist": "Geneticist", "division": "Narayanganj", "location": "Narayanganj Genetic Health Clinic", "booking_amount": { "new": 3400, "old": 1700 }, "booking": 12526645, "email": "ameer.hossain@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Fariha Rahman", "description": "MBBS, MD in Occupational Medicine", "specialist": "Occupational Medicine specialist", "division": "Cox's Bazar", "location": "Cox's Bazar Occupational Health Center", "booking_amount": { "new": 3500, "old": 1750 }, "booking": 12654745, "email": "fariha.rahman@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Shamsul Alam", "description": "MBBS, MD in Environmental Medicine", "specialist": "Environmental Medicine specialist", "division": "Jashore", "location": "Jashore Environmental Health Clinic", "booking_amount": { "new": 3600, "old": 1800 }, "booking": 12754754, "email": "shamsul.alam@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Ruksana Sultana", "description": "MBBS, MD in Family Medicine", "specialist": "Family Medicine specialist", "division": "Bogra", "location": "Bogra Family Health Center", "booking_amount": { "new": 3700, "old": 1850 }, "booking": 12852565, "email": "ruksana.sultana@example.com" },
        { "image": "public/image/defaultimg.jpg", "name": "Dr. Tanvir Rahman", "description": "MBBS, MD in Community Medicine", "specialist": "Community Medicine specialist", "division": "Panchagarh", "location": "Panchagarh Community Health Center", "booking_amount": { "new": 3800, "old": 1900 }, "booking": 12952221, "email": "tanvir.rahman@example.com" }
      
      
];

module.exports = {data : sampleData};